# Copyright (C) 2023 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker compose up
#           docker compose exec netshoot bash
#               busybox
#               nslookup postgres
#               ping postgres
#               openssl s_client -tls1_3 -trace postgres:5432
#               openssl s_client -tls1_3 -trace keycloak:8443
#               openssl s_client -tls1_3 -trace buch:3000
#
#               curl --tlsv1.3 --http2 --verbose --insecure https://buch:3000/rest/1
#               curl --tlsv1.3 --http2 --verbose --insecure --data 'username=admin&password=p' --header 'Content-Type: application/x-www-form-urlencoded' https://buch:3000/auth/token
#               curl --verbose http://keycloak:8080/realms/nest/.well-known/openid-configuration
#               curl --verbose --data 'username=admin&password=p&grant_type=password&client_id=nest-client&client_secret=0eoZjeaIa0SdAIdTwMRQofJ82ne3afUl' --header 'Content-Type: application/x-www-form-urlencoded' http://keycloak:8080/realms/nest/protocol/openid-connect/token
#
#               ip addr
#               ifconfig
#               ip route show
#               exit
#           docker compose down

services:
  netshoot:
    image: nicolaka/netshoot:v0.13
    command:
      [
        "sh",
        "-c",
        "echo 'Container mit netshoot ist gestartet.' && sleep infinity",
      ]
    networks: [acme-network]
    hostname: netshoot
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 768M

# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects#answer-48024244
networks:
  acme-network:
    name: acme-network
